export interface MemeTemplate {
  id: string;
  name: string;
  url: string;
  description: string;
  defaultTop?: string;
  defaultBottom?: string;
}

export interface MemeText {
  top: string;
  bottom: string;
}

export { MEME_TEMPLATES } from './data/memeTemplates';

export const RANDOM_MEME_TEXTS: MemeText[] = [
  { top: "Quand le code fonctionne enfin", bottom: "Mais tu n'as absolument aucune idée de pourquoi" },
  { top: "POV: Tu commences ta journée de dev", bottom: "Il est déjà 16h et tu as juste bu trois cafés" },
  { top: "Moi disant oui à un appel de \"5 minutes\"", bottom: "Trois heures plus tard, on parle de physique quantique" },
  { top: "Le stagiaire qui pousse son code directement en prod", bottom: "Un vendredi soir à 17h59 précis" },
  { top: "Quand on me demande poliment", bottom: "Si j'ai réussi à bien dormir cette nuit" },
  { top: "Moi devant mes finances personnelles", bottom: "Après avoir acheté un quatrième café crème à 6€50" },
  { top: "La panique totale et instantanée", bottom: "Quand mon téléphone n'est plus dans ma poche droite" },
  { top: "Moi expliquant sérieusement à mon chat", bottom: "Pourquoi je dois partir travailler pour lui payer ses croquettes" },
  { top: "Quand le professeur annonce joyeusement", bottom: "\"Vous pouvez vous mettre par groupes de deux\"" },
  { top: "Ma jauge de motivation le lundi matin", bottom: "Erreur 404 : Motivation non trouvée dans le système" },
  { top: "Moi après seulement 5 minutes de travail acharné", bottom: "\"Allez, une petite pause bien méritée de deux heures\"" },
  { top: "Quand j'arrive à écrire trois lignes de code CSS", bottom: "📈 STONKS" },
  { top: "\"J'ai lu et j'accepte les conditions d'utilisation\"", bottom: "Le plus grand et splendide mensonge de l'histoire humaine" },
  { top: "Quand tu fermes un onglet important", bottom: "Et que tu oublies immédiatement ce que tu cherchais à la base" },
  { top: "\"Ne t'inquiète pas, ça marche sur ma machine !\"", bottom: "La phrase de réconfort préférée de tous les développeurs" },
  { top: "Quand le livreur Uber Eats approche enfin de ma rue", bottom: "Mon rythme cardiaque fait soudainement un bond de géant" },
  { top: "Moi expliquant mon propre code écrit l'an dernier", bottom: "\"Franchement, c'est clairement l'œuvre d'un grand malade\"" },
  { top: "Quand tu ouvres le réfrigérateur pour la 5ème fois", bottom: "En espérant de tout cœur que de super plats soient apparus" },
  { top: "Moi faisant de grands signes de tête approbateurs", bottom: "Alors que je n'entends rien à cause du bruit de fond" },
  { top: "Quand tu te réveilles pile 5 minutes avant ton réveil", bottom: "La trahison ultime orchestrée par ton propre corps" },
  { top: "Le professeur : \"L'examen sera très simple\"", bottom: "L'examen en question : Sujet de niveau doctorat d'astrophysique" },
  { top: "Quand je regarde mon solde de compte bancaire", bottom: "Après un week-end pourtant qualifié de \"très raisonnable\"" },
  { top: "Moi criant dans toute la maison \"Je pars dans 5 minutes !\"", bottom: "Alors que je n'ai toujours pas allumé la douche" },
  { top: "Les cookies obligatoires sur les sites web", bottom: "\"Tout accepter\" frénétiquement juste de peur de rater l'article" },
  { top: "Quand tu essaies simplement d'ajuster une image en CSS", bottom: "Tout le reste de la mise en page du site s'autodétruit" },
  { top: "Moi tentant de calculer mentalement à 7h du matin", bottom: "Si je peux décemment me rendormir pendant encore 12 minutes" },
  { top: "Quand tu marches sur un Lego en pleine obscurité", bottom: "Une douleur atroce encore non répertoriée par la médecine" },
  { top: "Quand ton alarme de téléphone commence à sonner", bottom: "Et que tu regrettes amèrement de devoir gagner ta vie" },
  { top: "\"Promis, aujourd'hui je ne vais absolument rien acheter !\"", bottom: "Rend visite compulsivement à treize boutiques de sneakers" },
  { top: "Ton cerveau à 3h du matin sans crier gare", bottom: "\"Dis-moi, tu te souviens de cette humiliation de 2012 ?\"" },
  { top: "Quand tu écris accidentellement \"Bojnour\"", bottom: "Et que tu n'oses plus jamais répondre à la conversation de groupe" },
  { top: "Quand tu entends le son de ta propre voix dans un vocal", bottom: "\"Attends, c'est vraiment ma voix de canard boiteux ?\"" },
  { top: "Moi à l'entretien d'embauche : \"Le stress me motive !\"", bottom: "Moi au premier bug léger : Fond en larmes dans les toilettes" },
  { top: "Quand tu commandes un gadget inutile sur internet à 23h", bottom: "Et que tu attends le facteur sur le pas de la porte à 8h" },
  { top: "Quand tu sors de table après le goûter chez ta grand-mère", bottom: "Et que tu as sérieusement besoin d'un transpalette pour bouger" },
  { top: "Quand le prof d'anglais cherche une victime du regard", bottom: "Moi qui deviens soudain fasciné par la marque de ma gomme" },
  { top: "Quand le code que tu viens d'écrire compile du premier coup", bottom: "C'est suspect... Beaucoup trop suspect pour être honnête" },
  { top: "Quand tu voulais juste regarder l'heure sur ton écran", bottom: "Et que tu finis par scroller sur ton fil d'actus durant 1h" },
  { top: "\"Je vais me coucher vraiment super tôt ce soir, juré !\"", bottom: "Il est 4h45 et je regarde comment fabriquer un arc médiéval" },
  { top: "Quand tu croises ton professeur en dehors de l'école", bottom: "\"Mais attends... Ils ont une vraie vie de civil ?\"" },
  { top: "Moi lorsque je reçois une notification de message", bottom: "\"Quelqu'un pense à moi !\" / \"Payez votre facture impayée\"" },
  { top: "Quand le programme ne plante pas du tout", bottom: "Mais qu'il fait n'importe quoi sauf ce que tu voulais qu'il fasse" },
  { top: "Quand tu te prépares en urgence pour un appel Teams", bottom: "Chemise italienne repassée en haut, short de nuit en bas" },
  { top: "Quand tu perds tes écouteurs fétiches dans le bus", bottom: "Et que tu dois soudainement écouter la rumeur du monde" },
  { top: "Quand tu tentes de séparer les sachets de fruits", bottom: "Au rayon primeur du supermarché avec les mains sèches" },
  { top: "Moi essayant de dépanner le Wi-Fi de toute la famille", bottom: "En appliquant la technique secrète : Débrancher et rebrancher" },
  { top: "Quand tu cliques fébrile sur \"Mot de passe oublié\"", bottom: "Le site : \"Votre nouveau mot de passe doit être différent d'avant\"" },
  { top: "Moi et mon sens légendaire de l'orientation", bottom: "Réussit à se perdre dans un couloir sans aucune intersection" },
  { top: "Quand tu poses poliment une question sur un forum d'aide", bottom: "Et que la bête réponse reçue est juste \"Laisse tombé g trouvé\"" },
  { top: "Moi essayant de reprendre doucement une activité sportive", bottom: "\"Voilà, j'ai couru après le bus, vive la santé, à nous le kebab\"" },
  { top: "Quand l'application GPS crie \"Faites demi-tour immédiatement !\"", bottom: "On sent tout le jugement sarcastique du synthétiseur de voix" },
  { top: "Quand tu viens de terminer le dernier épisode de ta série", bottom: "Et que tu ressens un grand vide existentiel au fond de ton âme" },
  { top: "Quand tu as exactement 42 onglets ouverts en même temps", bottom: "Et qu'un bruit de pub surgit mais impossible de trouver d'où" },
  { top: "Quand un collègue veut faire une démonstration sur ton ordi", bottom: "Et qu'il commence à taper une lettre suspecte dans l'URL" },
  { top: "Moi face à une explication limpide et parfaitement mathématique", bottom: "\"Euh... Oui d'accord... Vu comme ça c'est plus clair...\"" },
  { top: "Quand tu retrouves par miracle une pièce de 2€ dans un jean", bottom: "Je suis riche. Je m'achète un pain au chocolat et une île privée" },
  { top: "Quand l'enseignant efface l'intégralité du tableau", bottom: "Alors que tu avais péniblement noté le titre du chapitre" },
  { top: "Quand tu tentes d'expliquer une blague très drôle", bottom: "Mais que personne ne rit et que tu t'enfonces dans la gêne" },
  { top: "Quand tu guettes impatiemment la livraison de ton super colis", bottom: "Et que le moindre bruit de moteur te fait sursauter de joie" },
  { top: "Quand tu as trouvé la position de sommeil parfaite", bottom: "Et que ton corps décide d'avoir une folle envie d'aller boire" },
  { top: "Le samedi et le dimanche qui filent en 4 secondes", bottom: "Face au mardi après-midi qui semble durer l'éternité" },
  { top: "Moi tentant maladroitement de faire un gentil compliment", bottom: "\"Dis donc, tu es quand même vachement moins fatigué aujourd'hui\"" },
  { top: "Quand je regarde mon historique git commit d'il y a 10 jours", bottom: "\"Mais quel est l'abruti sans cerveau qui a écrit cette bouse ?\"" },
  { top: "Quand le prof spécifie que le devoir est \"entièrement facultatif\"", bottom: "L'univers entier oublie instantanément l'existence de ce devoir" },
  { top: "Quand tu commences un e-mail professionnel par :", bottom: "\"Sauf erreur de ma part...\" (Traduction : Tu as tort, assume)" },
  { top: "Quand tu t'étouffes lamentablement avec ta propre salive", bottom: "Et que tu fais mine que tout est sous contrôle en devenant rouge" },
  { top: "Le serveur : \"Bon appétit à vous !\"", bottom: "Moi : \"Merci, vous de même !\" (S'exile sur une autre planète)" },
  { top: "Quand l'application Uber Eats affiche \"Votre coursier arrive dans 1 min\"", bottom: "Moi collé à l'œilleton de ma porte comme une sentinelle romaine" },
  { top: "Quand tu as l'illumination divine pour résoudre un bug complexe", bottom: "Exactement au moment précis où tu mets ton manteau pour partir" },
  { top: "\"Cette semaine, je gère drastiquement mes dépenses courantes\"", bottom: "Ah, regardez, des chaussons en forme de requin à 60 euros !" },
  { top: "Quand ton chat te fixe longuement sans cligner des yeux", bottom: "Sûrement en train de planifier ma disparition mystérieuse" },
  { top: "Quand l'enseignant prononce enfin ton nom de famille", bottom: "Et que tu te lèves comme un condamné marchant vers l'échafaud" },
  { top: "Quand la connexion Wi-Fi s'arrête durant 30 secondes", bottom: "Moi face au vide intersidéral de l'existence sans internet" },
  { top: "\"Ne t'inquiète pas, le montage de ce meuble est ultra simple\"", bottom: "Requiert quatre diplômes d'ingénieur et deux packs de bière" },
  { top: "Quand tu rédiges un magnifique paragraphe plein d'amour", bottom: "Et que la réponse universelle reçue est juste \"ok.\"" },
  { top: "Quand tu débarques au magasin en ayant oublié ta liste de courses", bottom: "\"Bon bah, ça va être spaghettis ketchup toute la semaine\"" },
  { top: "Quand le médecin ou le dentiste te demande si tu es sportif", bottom: "Moi pensant très fort aux escaliers empruntés avant-hier" },
  { top: "Quand ton portable vibre sur ta table de nuit à 2h du matin", bottom: "Moi persuadé du pire alors que c'est l'alerte d'un jeu de stratégie" },
  { top: "\"Je vais lire uniquement un tout petit chapitre pour m'endormir\"", bottom: "Oups... Le soleil brille dehors et j'ai dévoré toute la trilogie" },
  { top: "Quand tu te rends soudainement compte du temps qui passe", bottom: "La chanson de ton enfance a déjà fêté ses vingt ans d'existence" },
  { top: "Quand tu viens enfin de finir ton bon et généreux repas", bottom: "Et que tes yeux se posent sur la montagne de poêles sales dans l'évier" },
  { top: "Quand ton code est fantastique mais que la direction", bottom: "Demande de tout refaire parce qu'ils n'aiment plus trop la police" },
  { top: "Quand tu trouves enfin la motivation de vider tes placards", bottom: "Et que tu passes quatre heures à examiner un vieux jouet poussiéreux" },
  { top: "Quand tu oses commander un plat pimenté niveau trois sur cinq", bottom: "Toutes tes papilles demandent immédiatement l'asile politique" },
  { top: "Quand tu deconnectes ta clé USB sans faire l'éjection sécurisée", bottom: "Moi, le grand délinquant et anarchiste moderne de l'informatique" },
  { top: "Quand tu te mets à calculer précisément ton âge actuel", bottom: "Et que le chiffre obtenu te donne envie de t'acheter de la tisane" },
  { top: "Quand tu tentes d'exécuter une recette complexe de grand chef", bottom: "Le résultat visuel est plus proche de l'accident nucléaire" },
  { top: "Quand tu aperçois une vague connaissance dans la rue face à toi", bottom: "Moi devenant subitement captivé par la texture d'un mur" },
  { top: "Quand ton smartphone fait une chute de deux mètres face au sol", bottom: "Les cinq secondes les plus angoissantes du millénaire en cours" },
  { top: "Quand l'équipe nationale gagne alors que tu as juste zappé dessus", bottom: "\"INCROYABLE ! On a fait un match absolument phénoménal !\"" },
  { top: "Quand tu parviens à ouvrir un pot de confiture récalcitrant", bottom: "Sensation inégalée d'être l'humain le plus fort de la terre" },
  { top: "Quand ton conseiller d'orientation te demande ton plan d'avenir", bottom: "\"Déjà, survivre jusqu'à vendredi ce serait un exploit monumental\"" },
  { top: "La panique magique absolue qui te traverse", bottom: "Quand tu réalises que ton micro était resté ouvert sur la réunion" },
  { top: "Quand tu regardes attentivement une vieille photo de toi ado", bottom: "\"Mais quelle loi m'a autorisé à arborer cette coiffure immonde ?\"" },
  { top: "Quand l'ordinateur fait un effrayant bruit de turbine d'avion", bottom: "\"S'il te plaît mon vieux, ne me lâche pas maintenant...\"" },
  { top: "Quand tu te réveilles en sursaut persuadé d'être en retard", bottom: "Puis tu te rappelles qu'on est en fait un joli dimanche matin" },
  { top: "Quand on te félicite chaleureusement pour les résultats obtenus", bottom: "Alors que tu as improvisé de A à Z en fermant les yeux" },
  { top: "Quand tu passes devant ton miroir de salle de bain à 3h", bottom: "Et que tu juges sévèrement ta posture de crevette en fin de vie" },
  { top: "Quand le mème créé est d'une splendeur incomparable", bottom: "☕ Prends mon haut-vote et va-t'en d'ici" }
];
